In [ ]:


import torch

In [ ]:

torch.where((torch.tensor([0.5,0.6,0.3,0.1,0.1])>0.2))[0].tolo

tensor([0, 1, 2])

In [25]:
a =[0.5,0.6,0.3,0.1,0.1]
b =  [0.2,0.1,0.5,0.5]

In [78]:
probs  = torch.rand((4,6,3))

In [79]:
probs

tensor([[[0.6185, 0.7288, 0.2398],
         [0.7009, 0.9130, 0.7323],
         [0.2404, 0.2734, 0.2596],
         [0.2148, 0.9736, 0.7032],
         [0.9486, 0.1498, 0.6778],
         [0.3001, 0.2628, 0.3610]],

        [[0.5326, 0.6760, 0.0292],
         [0.1836, 0.0301, 0.7603],
         [0.3950, 0.4179, 0.4796],
         [0.4680, 0.2768, 0.8559],
         [0.5601, 0.2524, 0.3995],
         [0.4313, 0.5117, 0.2295]],

        [[0.4894, 0.0992, 0.7817],
         [0.3864, 0.0540, 0.9232],
         [0.7317, 0.0743, 0.5408],
         [0.3922, 0.2321, 0.6779],
         [0.9343, 0.5977, 0.8387],
         [0.4402, 0.2964, 0.3840]],

        [[0.5446, 0.2152, 0.6317],
         [0.0290, 0.7705, 0.4352],
         [0.6312, 0.6371, 0.4633],
         [0.1592, 0.9377, 0.5351],
         [0.5350, 0.9971, 0.2192],
         [0.4049, 0.7985, 0.1556]]])

In [82]:
probs[:,[True,True,False,False,True,False],:]

tensor([[[0.6185, 0.7288, 0.2398],
         [0.7009, 0.9130, 0.7323],
         [0.9486, 0.1498, 0.6778]],

        [[0.5326, 0.6760, 0.0292],
         [0.1836, 0.0301, 0.7603],
         [0.5601, 0.2524, 0.3995]],

        [[0.4894, 0.0992, 0.7817],
         [0.3864, 0.0540, 0.9232],
         [0.9343, 0.5977, 0.8387]],

        [[0.5446, 0.2152, 0.6317],
         [0.0290, 0.7705, 0.4352],
         [0.5350, 0.9971, 0.2192]]])

In [76]:
probs[]

SyntaxError: invalid syntax (318772729.py, line 1)

In [59]:
probs

tensor([[0.4854, 0.8016, 0.7681, 0.5763, 0.7428, 0.1085],
        [0.8612, 0.0792, 0.8064, 0.4573, 0.9792, 0.4687],
        [0.7405, 0.4843, 0.7568, 0.6274, 0.9357, 0.2981],
        [0.4989, 0.6844, 0.8742, 0.5287, 0.3607, 0.4880]])

In [60]:
probs.shape[0]

4

In [61]:
t_index = []

In [62]:
for i in range(probs.shape[0]):
    t_index.append(list(set(probs[i].topk(3).indices.tolist()) & set(torch.where(probs[i]>0.8)[0].tolist())))


In [63]:
t_index

[[1], [0, 2, 4], [4], [2]]

In [ ]:
probs.topk(3).indices.tolist()

[[3, 0, 5], [2, 5, 1], [4, 3, 5], [3, 2, 4]]

In [83]:
top_k=4
top_p=0.44

In [90]:
input = torch.rand(4,10)
input

tensor([[0.4718, 0.7627, 0.1028, 0.6829, 0.7008, 0.4306, 0.9011, 0.6310, 0.8286,
         0.5866],
        [0.8487, 0.8287, 0.1724, 0.2686, 0.3664, 0.4742, 0.6294, 0.1582, 0.5105,
         0.2058],
        [0.8205, 0.2445, 0.4401, 0.4883, 0.2959, 0.5463, 0.0580, 0.5475, 0.8959,
         0.9652],
        [0.8909, 0.3214, 0.0567, 0.4232, 0.8666, 0.3039, 0.9832, 0.3146, 0.2329,
         0.0129]])

In [91]:
probs =  torch.rand(4,5)
probs

tensor([[0.3795, 0.5996, 0.4773, 0.8309, 0.6507],
        [0.6376, 0.8686, 0.5289, 0.4131, 0.6857],
        [0.1437, 0.0103, 0.0287, 0.8736, 0.4511],
        [0.7975, 0.4321, 0.0290, 0.6629, 0.8807]])

In [94]:
torch.cat([probs, input], dim=0)

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 5 but got size 10 for tensor number 1 in the list.

In [2]:
import torch

In [6]:
A1 = torch.rand((4,4,5))
A1 

tensor([[[0.2401, 0.1644, 0.2737, 0.8294, 0.9236],
         [0.7138, 0.6151, 0.5161, 0.4204, 0.6970],
         [0.3435, 0.1412, 0.8848, 0.6534, 0.0099],
         [0.4525, 0.8536, 0.2920, 0.2695, 0.2196]],

        [[0.0451, 0.4182, 0.4266, 0.2169, 0.5508],
         [0.2618, 0.0512, 0.7138, 0.3143, 0.6830],
         [0.0033, 0.1513, 0.9564, 0.6689, 0.8202],
         [0.5793, 0.9369, 0.5686, 0.4347, 0.1702]],

        [[0.3093, 0.0196, 0.9611, 0.4234, 0.8789],
         [0.7472, 0.4488, 0.7151, 0.3405, 0.5108],
         [0.7340, 0.1809, 0.7453, 0.5779, 0.4780],
         [0.8406, 0.9627, 0.9879, 0.4560, 0.0286]],

        [[0.0158, 0.0327, 0.1231, 0.5465, 0.2570],
         [0.4393, 0.8853, 0.4639, 0.7628, 0.5805],
         [0.1462, 0.9114, 0.7590, 0.3967, 0.8761],
         [0.9251, 0.8028, 0.6100, 0.0841, 0.3723]]])

In [5]:
W1 = torch.rand((5,8))
W1 

tensor([[0.2424, 0.4696, 0.5665, 0.8987, 0.4447, 0.9128, 0.1825, 0.7266],
        [0.1279, 0.1244, 0.7261, 0.6257, 0.2772, 0.0330, 0.9556, 0.4892],
        [0.0318, 0.5170, 0.1989, 0.3032, 0.2243, 0.9698, 0.2876, 0.3916],
        [0.9605, 0.4734, 0.3125, 0.2945, 0.1490, 0.5560, 0.4458, 0.8436],
        [0.4869, 0.0784, 0.2158, 0.1179, 0.9149, 0.4963, 0.6837, 0.9206]])

In [8]:
O1 = torch.einsum('bsh,he->bse',A1,W1)
O1.shape

torch.Size([4, 4, 8])

In [11]:
O2 = torch.rand((2,2,5,6))
O2

tensor([[[[0.6440, 0.4123, 0.7863, 0.3392, 0.5438, 0.4703],
          [0.4157, 0.1365, 0.2024, 0.2490, 0.0709, 0.1560],
          [0.1981, 0.2367, 0.0307, 0.6474, 0.8140, 0.6256],
          [0.4430, 0.4911, 0.0702, 0.0985, 0.0083, 0.6785],
          [0.9494, 0.0321, 0.4218, 0.3278, 0.8746, 0.9816]],

         [[0.7489, 0.7357, 0.0583, 0.2438, 0.3030, 0.3543],
          [0.7547, 0.4958, 0.1374, 0.1456, 0.5002, 0.8504],
          [0.6448, 0.3692, 0.3396, 0.1664, 0.2948, 0.1767],
          [0.2943, 0.3341, 0.1520, 0.7814, 0.6709, 0.4692],
          [0.0113, 0.8544, 0.7069, 0.8553, 0.3395, 0.1499]]],


        [[[0.3165, 0.7993, 0.3375, 0.3799, 0.6874, 0.6277],
          [0.5842, 0.7782, 0.1043, 0.4746, 0.9089, 0.8649],
          [0.0511, 0.2676, 0.9178, 0.7082, 0.9381, 0.1592],
          [0.9879, 0.2747, 0.9171, 0.4386, 0.9731, 0.6427],
          [0.0582, 0.1416, 0.7605, 0.2959, 0.6163, 0.2472]],

         [[0.7904, 0.4796, 0.8276, 0.9027, 0.3291, 0.9490],
          [0.2071, 0.4215, 0.132

In [19]:
from einops import rearrange
O3 = rearrange(O2,'b s n e -> (b s) n e')
O3

tensor([[[0.6440, 0.4123, 0.7863, 0.3392, 0.5438, 0.4703],
         [0.4157, 0.1365, 0.2024, 0.2490, 0.0709, 0.1560],
         [0.1981, 0.2367, 0.0307, 0.6474, 0.8140, 0.6256],
         [0.4430, 0.4911, 0.0702, 0.0985, 0.0083, 0.6785],
         [0.9494, 0.0321, 0.4218, 0.3278, 0.8746, 0.9816]],

        [[0.7489, 0.7357, 0.0583, 0.2438, 0.3030, 0.3543],
         [0.7547, 0.4958, 0.1374, 0.1456, 0.5002, 0.8504],
         [0.6448, 0.3692, 0.3396, 0.1664, 0.2948, 0.1767],
         [0.2943, 0.3341, 0.1520, 0.7814, 0.6709, 0.4692],
         [0.0113, 0.8544, 0.7069, 0.8553, 0.3395, 0.1499]],

        [[0.3165, 0.7993, 0.3375, 0.3799, 0.6874, 0.6277],
         [0.5842, 0.7782, 0.1043, 0.4746, 0.9089, 0.8649],
         [0.0511, 0.2676, 0.9178, 0.7082, 0.9381, 0.1592],
         [0.9879, 0.2747, 0.9171, 0.4386, 0.9731, 0.6427],
         [0.0582, 0.1416, 0.7605, 0.2959, 0.6163, 0.2472]],

        [[0.7904, 0.4796, 0.8276, 0.9027, 0.3291, 0.9490],
         [0.2071, 0.4215, 0.1324, 0.3565, 0.3790, 

In [2]:
from enum import Enum

class MLPActivationType(Enum):
    RELU = "relu"
    GELU = "gelu"
    SILU = "silu"
    SIGMOID = "sigmoid"
    BILINEAR = "bilinear"


MLPActivationType.SILU

<MLPActivationType.SILU: 'silu'>

In [3]:
import torch.nn as nn

In [7]:
activation_map = {
        1: nn.SiLU(),
        "2": nn.ReLU(),
        MLPActivationType.GELU: nn.GELU(),
        MLPActivationType.SIGMOID: nn.Sigmoid(),
        MLPActivationType.BILINEAR: nn.Identity()
        }

In [ ]:
activation_map = {
        MLPActivationType.SILU: nn.SiLU(),
        MLPActivationType.RELU: nn.ReLU(),
        MLPActivationType.GELU: nn.GELU(),
        MLPActivationType.SIGMOID: nn.Sigmoid(),
        MLPActivationType.BILINEAR: nn.Identity()
        }
activation_type = MLPActivationType.BILINEAR



KeyError: 'activation_type'

In [10]:
Activation = activation_map["2"]
Activation

ReLU()