In [ ]:


import torch

In [ ]:

torch.where((torch.tensor([0.5,0.6,0.3,0.1,0.1])>0.2))[0].tolo

tensor([0, 1, 2])

In [25]:
a =[0.5,0.6,0.3,0.1,0.1]
b =  [0.2,0.1,0.5,0.5]

In [78]:
probs  = torch.rand((4,6,3))

In [79]:
probs

tensor([[[0.6185, 0.7288, 0.2398],
         [0.7009, 0.9130, 0.7323],
         [0.2404, 0.2734, 0.2596],
         [0.2148, 0.9736, 0.7032],
         [0.9486, 0.1498, 0.6778],
         [0.3001, 0.2628, 0.3610]],

        [[0.5326, 0.6760, 0.0292],
         [0.1836, 0.0301, 0.7603],
         [0.3950, 0.4179, 0.4796],
         [0.4680, 0.2768, 0.8559],
         [0.5601, 0.2524, 0.3995],
         [0.4313, 0.5117, 0.2295]],

        [[0.4894, 0.0992, 0.7817],
         [0.3864, 0.0540, 0.9232],
         [0.7317, 0.0743, 0.5408],
         [0.3922, 0.2321, 0.6779],
         [0.9343, 0.5977, 0.8387],
         [0.4402, 0.2964, 0.3840]],

        [[0.5446, 0.2152, 0.6317],
         [0.0290, 0.7705, 0.4352],
         [0.6312, 0.6371, 0.4633],
         [0.1592, 0.9377, 0.5351],
         [0.5350, 0.9971, 0.2192],
         [0.4049, 0.7985, 0.1556]]])

In [82]:
probs[:,[True,True,False,False,True,False],:]

tensor([[[0.6185, 0.7288, 0.2398],
         [0.7009, 0.9130, 0.7323],
         [0.9486, 0.1498, 0.6778]],

        [[0.5326, 0.6760, 0.0292],
         [0.1836, 0.0301, 0.7603],
         [0.5601, 0.2524, 0.3995]],

        [[0.4894, 0.0992, 0.7817],
         [0.3864, 0.0540, 0.9232],
         [0.9343, 0.5977, 0.8387]],

        [[0.5446, 0.2152, 0.6317],
         [0.0290, 0.7705, 0.4352],
         [0.5350, 0.9971, 0.2192]]])

In [76]:
probs[]

SyntaxError: invalid syntax (318772729.py, line 1)

In [59]:
probs

tensor([[0.4854, 0.8016, 0.7681, 0.5763, 0.7428, 0.1085],
        [0.8612, 0.0792, 0.8064, 0.4573, 0.9792, 0.4687],
        [0.7405, 0.4843, 0.7568, 0.6274, 0.9357, 0.2981],
        [0.4989, 0.6844, 0.8742, 0.5287, 0.3607, 0.4880]])

In [60]:
probs.shape[0]

4

In [61]:
t_index = []

In [62]:
for i in range(probs.shape[0]):
    t_index.append(list(set(probs[i].topk(3).indices.tolist()) & set(torch.where(probs[i]>0.8)[0].tolist())))


In [63]:
t_index

[[1], [0, 2, 4], [4], [2]]

In [ ]:
probs.topk(3).indices.tolist()

[[3, 0, 5], [2, 5, 1], [4, 3, 5], [3, 2, 4]]

In [83]:
top_k=4
top_p=0.44

In [90]:
input = torch.rand(4,10)
input

tensor([[0.4718, 0.7627, 0.1028, 0.6829, 0.7008, 0.4306, 0.9011, 0.6310, 0.8286,
         0.5866],
        [0.8487, 0.8287, 0.1724, 0.2686, 0.3664, 0.4742, 0.6294, 0.1582, 0.5105,
         0.2058],
        [0.8205, 0.2445, 0.4401, 0.4883, 0.2959, 0.5463, 0.0580, 0.5475, 0.8959,
         0.9652],
        [0.8909, 0.3214, 0.0567, 0.4232, 0.8666, 0.3039, 0.9832, 0.3146, 0.2329,
         0.0129]])

In [91]:
probs =  torch.rand(4,5)
probs

tensor([[0.3795, 0.5996, 0.4773, 0.8309, 0.6507],
        [0.6376, 0.8686, 0.5289, 0.4131, 0.6857],
        [0.1437, 0.0103, 0.0287, 0.8736, 0.4511],
        [0.7975, 0.4321, 0.0290, 0.6629, 0.8807]])

In [94]:
torch.cat([probs, input], dim=0)

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 5 but got size 10 for tensor number 1 in the list.

In [ ]:
torch.stack
for i in range(probs.shape[0]):
    T_input = input[i, list(set(probs[i].topk(top_k).indices.tolist()) & set(torch.where(probs[i]>top_p)[0].tolist())), :]